export enum ErrorCodes {
    // User errors
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
    USER_UNAUTHORIZED = 'USER_UNAUTHORIZED',

    // Validation error
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    INVALID_EMAIL = 'INVALID_EMAIL',
    INVALID_PHONE = 'INVALID_PHONE',
    INVALID_PASSWORD = 'INVALID_PASSWORD',

    // T-shirts errors
    TSHIRT_NOT_FOUND = 'TSHIRT_NOT_FOUND',
    TSHIRT_ALREADY_EXISTS = 'TSHIRT_ALREADY_EXISTS',
    TSHIRT_INVALID_DATA = 'TSHIRT_INVALID_DATA',

    // Order errors
    ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
    ORDER_INVALID_STATUS = 'ORDER_INVALID_STATUS',

    // Payment errors
    PAYMENT_FAILED = 'PAYMENT_FAILED',
    PAYMENT_INVALID = 'PAYMENT_INVALID',

    // Server errors
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}