export enum SuccessCodes {
    // User success codes
    USER_FOUND = 'USER_FOUND',
    USER_CREATED = 'USER_CREATED',
    USER_UPDATED = 'USER_UPDATED',
    USER_DELETED = 'USER_DELETED',
    USER_LOGGED_IN = 'USER_LOGGED_IN',
    USER_REGISTERED = 'USER_REGISTERED',
    USER_LOGOUT = 'USER_LOGOUT',

    // T-Shirt success codes
    TSHIRT_FOUND = 'TSHIRT_FOUND',
    TSHIRT_CREATED = 'TSHIRT_CREATED',
    TSHIRT_UPDATED = 'TSHIRT_UPDATED',
    TSHIRT_DELETED = 'TSHIRT_DELETED',

    // Order success codes
    ORDER_FOUND = 'ORDER_FOUND',
    ORDER_CREATED = 'ORDER_CREATED',
    ORDER_UPDATED = 'ORDER_UPDATED',
    ORDER_DELETED = 'ORDER_DELETED',

    // Cart
    CART_ADDED = 'CART_ADDED',

    // Cart items
    CART_ITEMS_FOUND = 'CART_ITEMS_FOUND',

    // General success codes
    OPERATION_SUCCESSFUL = 'OPERATION_SUCCESSFUL',
    DATA_RETRIEVED = 'DATA_RETRIEVED',
    VALIDATION_SUCCESSFUL = 'VALIDATION_SUCCESSFUL',

    // JWT Tokens success codes
    TOKENS_REFRESHED = 'TOKENS_REFRESHED',
}